# Sample .travis.yml for R projects

language: r
cran: http://cran.at.r-project.org
cache: packages
sudo: false
warnings_are_errors: false
bioc_required: true

# Add GDAL, GEOS, proj, and units2 dependencies.
before_install:
  - Rscript -e 'update.packages(ask = FALSE)'
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh

addons:
  apt:
    packages:
      - sudo add-apt-repository -y ppa:ubuntugis/ppa
      - sudo apt-get -y --force-yes update -qq
      - sudo apt-get install -y libgsl0-dev libudunits2-dev libproj-dev libcurl4-openssl-dev libgeos-dev libgdal-dev gdal-bin


notifications:
  email:
    on_success: change
    on_failure: change

os:
  - linux
  #- osx

#matrix:
#  allow_failures:
#    - os: osx

env:
  global:
    - NOT_CRAN: FALSE
    - R_CHECK_ARGS="--as-cran --timings"
    - R_CHECK_TIME="TRUE"
    - R_CHECK_TESTS="TRUE"
    - _R_CHECK_TIMINGS_="0"
    - _R_CHECK_FORCE_SUGGESTS_=FALSE
    - MAKEFLAGS="-j 2"
    - TRAVIS_CXXFLAGS="-Wall -Wextra -pedantic -Werror"
    - R_REMOTES_NO_ERRORS_FROM_WARNINGS=TRUE
    - _R_CHECK_SYSTEM_CLOCK_=FALSE


# Binary versions of packages to reduce build time.
r_binary_packages:
  - data.table
  - dplyr
  - markdown
  - readr
  - rlang
  - rmarkdown
  - stringi
  - tidyr
  - tibble
  - ggplot2
